# 服务名称
spring:
  application:
    name: order-consumer

# 服务端口号
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: ttp://admin:123456@eureka7001.com:7001/eureka/,http://admin:123456@eureka7002.com:7002/eureka,http://admin:123456@eureka7003.com:7003/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

