server:
  port: 9527

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: payment_save # 路由ID，没有固定规则但要求唯一，建议配合服务名使用
          uri: http://localhost:8001 # 提供服务的路由地址
          predicates:
            - Path=/payment/save # 断言 路径相匹配的进行路由

        - id: payment_getPayment # 路由ID，没有固定规则但要求唯一，建议配合服务名使用
#          uri: http://localhost:8001 # 提供服务的路由地址
          uri: lb://payment-service # 负载均衡动态创建路由
          predicates:
            - Path=/payment/getPayment/** # Path断言 路径相匹配的进行路由 ** 表示匹配路径参数@PathVariable
#            - After=2020-10-22T23:31:17.596614+08:00[Asia/Shanghai] # Before断言 设置什么时间后可以进行路由 时间生成方法见 com.fcwalkers.learn.springcloud.gateway.PredicatesFactoryTest.getBeforeOrAfterTime


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka7001.com:7001/eureka/,http://admin:123456@eureka7002.com:7002/eureka,http://admin:123456@eureka7003.com:7003/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}